### ISSUE TITLE
MouseDrag/Release issue

### ISSUE THREAD

**Issue by appstruction** [mzusin/toolcool-range-slider#13]
When you grab the slider-circle, move the mouse up or down on the screen for e.g. 2 cm above the slider circle, it is still possible to move the slide to the left or right, but on release, the action is not triggered.

**Comment by mzusin** [comment]
When you say that the action is not triggered, what do you mean? Change event from [here](https://toolcool-range-slider.mzsoft.org/pages/events.html)?

**Comment by appstruction** [comment]
I use "onMouseUp" listener, and when the mouse isn't on the slider circle, you can still move the slider left/right but the "onMouseUp" event isn't fired.

**Comment by mzusin** [comment]
Should be fixed now - https://cdn.jsdelivr.net/npm/toolcool-range-slider@4.0.27/dist/toolcool-range-slider.min.js

**Comment by appstruction** [comment]
No, it's not fixed. To reproduce:

A slider, range 1 to 100, grab the slider-circle --> move to 5 but don't release the mouse button, now move up e.g. 2 cm above the slider circle --> move to 10, you can still move the slider-circle, and now release the mouse button. The event isn't fired, because you are not directly on the slider-circle.

**Comment by appstruction** [comment]
[example in fiddle](https://jsfiddle.net/phiwu/1ntp67ks/)
Please open developer console for log output.

1. (working) Grab the slider circle, move a few steps to the right, release mouse button --> output in developer console
2. (not working) Grab the slider circle, move a few steps to the right, don't release mouse button, move up while holding the mouse button, move a few steps to the right, release mouse button --> no output in developer console.

**Comment by mzusin** [comment]
Please replace https://cdn.jsdelivr.net/npm/toolcool-range-slider/dist/toolcool-range-slider.min.js with https://cdn.jsdelivr.net/npm/toolcool-range-slider@4.0.27/dist/toolcool-range-slider.min.js and it will work well. JSdelivr CDN has some cache and it takes time while its propagated. 

You can see my fiddle here:
https://jsfiddle.net/rosehip/j28dzakq/4/

**Comment by appstruction** [comment]
I've updated the example with 4.0.27 and some settings: [https://jsfiddle.net/phiwu/1ntp67ks/4/](https://jsfiddle.net/phiwu/1ntp67ks/4/)

**Comment by mzusin** [comment]
In your example, when you go up, you are outside of the jsfiddle iframe window. In this case indeed mouseup event is not triggered. But it's triggered if you inside the window, for example if you go down or if the slider has top margin.

https://github.com/mzusin/toolcool-range-slider/assets/128969497/c0b0a162-9453-48be-953e-a5c7dc7d834b

**Comment by appstruction** [comment]
The real problem is, that it is possible to move the slider even if you are not directly on the slider handle. Is there a way to disable this behaviour?

It is a problem if there are many sliders and someone is using it the not the way it should be used.

[https://jsfiddle.net/phiwu/1ntp67ks/13/](https://jsfiddle.net/phiwu/1ntp67ks/13/)

**Comment by mzusin** [comment]
This behavior is intended because it is very difficult to move the slider pointer along a thin line.
